config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create', as: :users

  get 'login' => 'main#new'
  post 'login' => 'main#create'

  get 'logout' => 'sessions#destroy'
  get 'feed' => 'sessions#feed'

  get 'collection' => 'gifs#collection'
  get 'profile' => 'posts#profile'

  get '/search', to: 'users#search'

  resources :sessions

  resources :users 

  resources :gifs

  resources :friendships

  resources :posts

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

	belongs_to :user
	belongs_to :friend, :class_name => "User"

end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	validates :password,
	presence: true,
	confirmation: true

	validates :password_confirmation,
	presence: true

	validates :email,
 	presence: true,
 	uniqueness: {case_sensitive: false},
 	format: {with: /@/}

 	validates :user_name,
 	uniqueness: {case_sensitive: false}

 	has_many :gifs
 	has_many :posts

 	has_many :friendships
 	has_many :friends, :through => :friendships

 	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
 	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

 	def self.authenticate email, password
		User.find_by_email(email).try(:authenticate, password)
	end

	def self.search(search)
	if search
	  where("user_name LIKE ?", "%#{search}%") 
	else
		return User.all
	end
end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  @users = User.all

  	def current_user
  		@current_user ||= User.find_by_id(session[:user_id])
  	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

	def create
		if !current_user.friendships.find_by_friend_id(params[:friend_id])
			@friendship = current_user.friendships.build(:friend_id => params[:friend_id])
			if @friendship.save
				redirect_to sessions_path
			else
				redirect_to sessions_path
			end
		else
			redirect_to sessions_path
		end
	end

	def destroy

		@friendship = current_user.friendships.find(params[:id])
		@friendship.destroy
		redirect_to sessions_path

	end

end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

	# if !@current_user
	#   	redirect_to root_path
 #  	end

	def collection
		if !@current_user
			redirect_to root_path
		else
		@user = current_user
		@users = User.all
		end
	end

	def new
		@gif = Gif.new
	end

	def create
		@user = current_user
		@gif = @user.gifs.create(url: params[:url])
		respond_to do |format|
   		format.json { head :ok }
 end
	end

	def show
		# @gif = Gif.create(url: params[:id])
		# redirect_to sessions_path
	end

	def destroy
		gif = Gif.find(params[:id])
		result=gif.delete
		render :json => {result:result}
	end


end

app/controllers/main_controller.rb
class MainController < ApplicationController


	def index
		if @current_user
		redirect_to sessions_path
	end
    @user = User.new
	end

	def new
		@user=User.new
	end

	def create
	  user = User.authenticate(params[:user][:email],
      params[:user][:password])

    if user
      session[:user_id] = user.id
      flash[:success] = 'You are now logged in.'
      redirect_to sessions_path
    else

      flash[:danger] = 'Invalid email or password.'
      redirect_to root_path
    end
	end

	private

	def user_params
	params.require(:user).permit(:email,:name,:password)
	end

  	def destroy
	    session[:user_id] = nil
	    flash[:info] = "You are logged out."
	    redirect_to root_path
	 end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def profile
		if !@current_user
			redirect_to root_path
		else
		@user = current_user
		@users = User.all
		end
	end

	def new
		@post = Post.new
	end

	def create
		@user = current_user
		@post = @user.posts.create(url: params[:url])
		respond_to do |format|
   		format.json { head :ok }
 end
	end

	def show
		# @post = post.create(url: params[:id])
		# redirect_to sessions_path
	end

	def destroy
		post = Post.find(params[:id])
		result=post.delete
		render :json => {result:result}
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


	@users = User.search("user")

	def index
		no_picture = Struct.new(:picture,:user_name,:friendships,:inverse_friends)
		@user = current_user || no_picture.new('https://pbs.twimg.com/profile_images/378800000822867536/3f5a00acf72df93528b6bb7cd0a4fd0c.jpeg','anonymous',[],[])
		@users = User.all
	end

	def feed
		if !@current_user
			redirect_to root_path
		else
		@posts=[]
		@user = current_user
		@users = User.search("user")
		@user.friends.each do |friend|
					friend.posts.each do |post|
						@posts	<< post
					end
				end
		@sorted_posts = @posts.sort_by{|e| e[:created_at]}.reverse
		end
	end

	def destroy
	session[:user_id] = nil
	flash[:info] = "You are logged out."
	redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# if !@current_user
	#   	redirect_to root_path
 #  	end

 	def index
	  @users = User.all
	end

	def new
    @user = User.new
	end

	def create

	if params[:user][:picture]
		uploaded_file = params[:user][:picture].path
	    cloudinary_file = Cloudinary::Uploader.upload(uploaded_file)
	else
		cloudinary_file="string";
	end

	@user = User.create(user_name: params[:user][:user_name],picture: cloudinary_file['public_id'],
		email: params[:user][:email],password: params[:user][:password],
		password_confirmation: params[:user][:password_confirmation]);
		if @user.persisted?
		  flash[:success] = "You are signed up! Login above."
		  redirect_to root_path
		else
	      flash[:danger] = @user.errors.full_messages.uniq.to_sentence
	      redirect_to root_path	
	    end

	end

	def search
		users = []
		User.search(params[:user_name]).each do |user|
			users.push({user_name: user.user_name,pic: user.picture,id: user.id})
		end
		render :json => users
	end

	def show
		no_picture = Struct.new(:picture,:user_name,:friendships,:inverse_friends)
		@user = current_user || no_picture.new('https://pbs.twimg.com/profile_images/378800000822867536/3f5a00acf72df93528b6bb7cd0a4fd0c.jpeg','anonymous',[],[])
		@user_show = User.find (params[:id])
		
		@sorted_posts = @user_show.posts.all.sort_by{|e| e[:created_at]}.reverse
	end

	private

	def user_params
	params.require(:user).permit(:user_name,:email,:password,:password_confirmation)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gifs/collection.html.erb
<div class="col-sm-3 pull-left" id="sidebar">
	<%= render "shared/sidebar" %>
</div>
<div class="col-sm-9 pull-right" id="mainView">
	<div id="userCollInfo">
		<%= cl_image_tag(@user.picture, :width => 140, :height => 140, :crop => :fill) %>
		<h1>Your gif collection.</h1>
		<span class="notification"></span>
		<hr>
	</div>
	<div class="mainScroll dimmed">
		<div id="collectionView">
			<% @current_user.gifs.each do |gif| %>
			<div class="imageDiv" imgurl="<%= gif.url %>" imgId="<%= gif.id %>" style="background-image: url(<%= gif.url %>);"><img class="show" src="https://cdn4.iconfinder.com/data/icons/geomicons/32/672382-expand-128.png" data-toggle="modal" data-target="#gifExpand"><img class="delete" src="http://freeiconbox.com/icon/256/12960.png"><img class="post" src="https://d30y9cdsu7xlg0.cloudfront.net/png/1490-200.png"></div>
			<% end %>
		</div>
	</div>
</div>	
<%= render "shared/usersearch" %>
<%= render "shared/expand" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatmapp</title>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  
  <link href='https://fonts.googleapis.com/css?family=Alfa+Slab+One|Viga|Passion+One|Jura|Marvel|Titillium+Web' rel='stylesheet' type='text/css'>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
	<%= yield %>
</div>
</body>
</html>

app/views/main/index.html.erb
<div id='login'>
<div class="logo">
g@
</div>
<div id="login_form">
<%= bootstrap_form_for :user, url: login_path do |u| %>
	<%= u.text_field :email, placeholder: "E-mail." %>
	<%= u.password_field :password, placeholder: "Password." %>
	<%= u.primary "Login." %> 
	<button type="button" class='btn btn-primary' data-toggle="modal" data-target="#signUp">
	Sign Up!
	</button>
<% end %>
</div>
<%= render "shared/flash" %>
<!-- Modal -->
<div class="modal fade" id="signUp" tabindex="1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      	<h2>Create an account!</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
      	<%= bootstrap_form_for @user, url: signup_path do |n| %>
      		<%= n.text_field :user_name, placeholder: "Desired user-name." %> 
          <%= n.file_field :picture %>
    			<%= n.text_field :email, placeholder: "E-mail." %>
    			<%= n.password_field :password, placeholder: "Password." %>
          <%= n.password_field :password_confirmation, placeholder:"Re-type password." %> 
          <div class="modal-footer">
          <%= n.primary "g@ me!" %>
      </div>
			<% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/posts/profile.html.erb
<div class="col-sm-3 pull-left" id="sidebar">
	<%= render "shared/sidebar" %>
</div>
<div class="col-sm-9 pull-right" id="mainView">
	<div id="userCollInfo">
		<%= cl_image_tag(@user.picture, :width => 140, :height => 140, :crop => :fill) %>
		<h1>Your public profile.</h1>
		<p class="notification"></p>
		<hr>
	</div>
	<div class="profScroll">
		<div id="profView">
			<% @current_user.posts.each do |post| %>
							<div class="well">
								<div class="opImgDiv" imgId="<%= post.id %>" imgUrl="<%= post.url %>">
								<img class="show" src="https://cdn4.iconfinder.com/data/icons/geomicons/32/672382-expand-128.png" data-toggle="modal" data-target="#gifExpand"><img class="delete" src="http://freeiconbox.com/icon/256/12960.png"><img class="post" src="https://d30y9cdsu7xlg0.cloudfront.net/png/18962-200.png"></div>
								<img src="<%= post.url %>">
								<p><%= post.created_at %></p>
							</div>
			<% end %>
		</div>
	</div>
</div>	
<%= render "shared/usersearch" %>
<%= render "shared/expand" %>

app/views/shared/_expand.html.erb
<div class="modal sm" id="gifExpand" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document" >
    <div class="modal-content">
      <div id="gifExpandImg">
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %> flash">
    <%= v %>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="seshLogo">
		g@
</div>
	<hr>
	<div id="userInfo">
		<div id='userPic'>
			<%= cl_image_tag(@user.picture, :width => 90, :height => 90, :crop => :fill) %>
		</div>
		<div id='userText'>
			<a href="/profile"><h4><%= @user.user_name %></h4></a>
			<ul class="nav nav-pills">
			  <li role="presentation"><%= link_to "Feed.", feed_path %></li>
			  <li role="presentation"><%= link_to "Collection.", collection_path %></li>
			  <li role="presentation"><%= link_to "Search.", sessions_path %></li>
			</ul>
			<% if @current_user %>
			<h6><%= link_to "Log-out.", logout_path %></h6>
			<% else %>
			<h6><%= link_to "Login / Sign-up.", root_path %></h6>
			<% end %>
		</div>	
	</div>
	<hr>
	<div id="userSearch">
	<form class="form-group">
		<input type="text" class="form-control" id="userSearchField" 
		placeholder="Search for users by user-name.">
		<button class="btn btn-primary" id="userSrchBtn" data-toggle="modal" data-target="#userSearchRslts">
		<span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
	</form>
	</div>
	<div id="followerFollowingInfo">
		<div id="following">
			<h4>Following.</h4>
			<hr>
			<ul>
				<% for friendship in @user.friendships %>
					<p>
					<%= cl_image_tag(friendship.friend.picture, :width => 30, :height => 30, :crop => :fill) %>
					<%= friendship.friend.user_name %> (<%= link_to "Profile.", friendship.friend %>)
					(<%= link_to "Unfollow.", friendship, :method => :delete %>)</p>
				<% end %>
			</ul>
		</div>
		<div id="followers">
			<h4>Followers</h4>
			<hr>
			<ul>
				<% for friendship in @user.inverse_friends %>
					<p>
					<%= cl_image_tag(friendship.picture, :width => 30, :height => 30, :crop => :fill) %>
					<%=h friendship.user_name %></p>
				<% end %>
			</ul>
		</div>
	</div>

app/views/shared/_usersearch.html.erb
<div class="modal sm fade" id="userSearchRslts" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">User search.</h3>
        <hr>
          <form class="form-group">
            <input type="text" class="form-control" id="userModSearchField" 
            placeholder="Search for users by user-name.">
            <button class="btn btn-primary" id="userModSrchBtn">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </form>
      </div>
      <div class="modal-body" id="usrSrchRslts">
       
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-sm-3 pull-left" id="sidebar">
	<%= render "shared/sidebar" %>
</div>
<div class="col-sm-9 pull-right" id="mainView">
	<div id="userShowInfo">
		<%= cl_image_tag(@user_show.picture, :width => 140, :height => 140, :crop => :fill) %>
		<h1><%= @user_show.user_name %></h1>
		<button class="followProfBtn btn btn-default" frndId="<%= @user_show.id %>">Follow.</button>
		<span class="notification"></span>
		<hr>
	</div>
	<div class="profScroll">
			<% @sorted_posts.each do |post| %>
							<div class="well">
								<h3><%= post.user.user_name %></h3>
								<%= cl_image_tag(post.user.picture, :width => 50, :height => 50, :crop => :fill) %>
								<div class="opImgDiv" imgurl="<%= post.url %>">
								<img class="show" src="https://cdn4.iconfinder.com/data/icons/geomicons/32/672382-expand-128.png" data-toggle="modal" data-target="#gifExpand"><img class="save" src="https://cdn4.iconfinder.com/data/icons/wirecons-free-vector-icons/32/add-128.png"><img class="post" src="https://d30y9cdsu7xlg0.cloudfront.net/png/1490-200.png"></div>
								<img src="<%= post.url %>">
								<p><%= post.created_at %></p>
							</div>
							<% end %>
	</div>
</div>	
<%= render "shared/usersearch" %>
<%= render "shared/expand" %>